// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn33dKBI3kXgWMy-Nnxsvu2QzTaO5Bdpw',
    appId: '1:1025861464872:web:176e24c05664952ace561d',
    messagingSenderId: '1025861464872',
    projectId: 'unifinder-86100',
    authDomain: 'unifinder-86100.firebaseapp.com',
    storageBucket: 'unifinder-86100.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rYscY5Thf07-WN7dAUJlLDp_fgzDZk0',
    appId: '1:1025861464872:android:affe11eae5d5324cce561d',
    messagingSenderId: '1025861464872',
    projectId: 'unifinder-86100',
    storageBucket: 'unifinder-86100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaas15n6I-fwlpsayMP2pBE6Qpuz4lqks',
    appId: '1:1025861464872:ios:a892f5f555208d33ce561d',
    messagingSenderId: '1025861464872',
    projectId: 'unifinder-86100',
    storageBucket: 'unifinder-86100.firebasestorage.app',
    iosBundleId: 'com.example.unifinderBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaas15n6I-fwlpsayMP2pBE6Qpuz4lqks',
    appId: '1:1025861464872:ios:a892f5f555208d33ce561d',
    messagingSenderId: '1025861464872',
    projectId: 'unifinder-86100',
    storageBucket: 'unifinder-86100.firebasestorage.app',
    iosBundleId: 'com.example.unifinderBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn33dKBI3kXgWMy-Nnxsvu2QzTaO5Bdpw',
    appId: '1:1025861464872:web:1fc6b842abc523a2ce561d',
    messagingSenderId: '1025861464872',
    projectId: 'unifinder-86100',
    authDomain: 'unifinder-86100.firebaseapp.com',
    storageBucket: 'unifinder-86100.firebasestorage.app',
  );
}
